### ISSUE TITLE
api method for transaction info ?

### ISSUE THREAD

**Issue by gagarin55** [ScorexProject/Scorex#72]
Hi guys!
Sorry for a stupid question,but is it possible to get particular transaction info by http api?
I didn't find any method at swagger definition :(

**Comment by catena2w** [comment]
You need to get transaction data by transaction id?

**Comment by gagarin55** [comment]
Yes, i think. I'm developing block explorer. It seems to be useful search txs by ID (signature i mean)

**Comment by catena2w** [comment]
For now there is no such a method, will be implemented in next release
