### ISSUE TITLE
preferable JSON style

### ISSUE THREAD

**Issue by gagarin55** [ScorexProject/Scorex#73]
Hi guys!

I'm thinking about json fields naming style in your project. Now you use '-' as separator. For instance: 'consensus-algo'. But in JavaScript it will be problem because we can't use '-' in variable's name.
There is workaround for JS: data["consenus-algo"] or data["some long name"].
But may be it will be more comfortable use something like '_' or camelCase? What do you think ?

I have just found Google Style : https://google.github.io/styleguide/jsoncstyleguide.xml

it's up to you, just want know your decision/opinion

**Comment by catena2w** [comment]
Fixed some places with incorrect json style.
If you find any more incorrect JSON responses - please, let us know!

**Comment by gagarin55** [comment]
Thank you for choice!
