### ISSUE TITLE
StackOverflow for incorrect settings.json

### ISSUE THREAD

**Issue by gagarin55** [ScorexProject/Scorex#75]
If we provide incorrect wallet file path to Wallet.scala we will have empty wallet seed and stuck in infinity loop:

in Wallet.scala

```
def readSeed(): Array[Byte] = Base58.decode(scala.io.StdIn.readLine()).getOrElse {
        println("Wallet seed should be correct Base58 encoded string.")
        readSeed()
      }
      readSeed()

```

Example:

```
    val walletFile = new java.io.File(s"/asdfasdfasdfasdftmp/wallet${Random.nextLong()}.dat")
    val w = new Wallet(Some(walletFile), "", None)
```

**Comment by tguinot** [comment]
In case of incorrect wallet file path, wouldn't it just throw an exception at database creation anyways?

`class Wallet(walletFileOpt: Option[File], password: String, seedOpt: Option[Array[Byte]]) extends ScorexLogging {

  private val NonceFieldName = "nonce"

  private val database: MVStore = walletFileOpt match {
    case Some(walletFile) =>
      //create parent folders then check their existence
      walletFile.getParentFile.mkdirs().ensuring(walletFile.getParentFile.exists())
      new MVStore.Builder().fileName(walletFile.getAbsolutePath).encryptionKey(password.toCharArray).compress().open()

    case None => new MVStore.Builder().open()
  }`

_walletFile.getParentFile.mkdirs().ensuring(walletFile.getParentFile.exists())_ throws an _java.lang.NullPointerException_ if the file doesn't exists on the path

**Comment by tguinot** [comment]
In case of incorrect wallet file path, wouldn't it just throw an exception at database creation anyways?

```
class Wallet(walletFileOpt: Option[File], password: String, seedOpt: Option[Array[Byte]]) extends ScorexLogging {

  private val NonceFieldName = "nonce"

  private val database: MVStore = walletFileOpt match {
    case Some(walletFile) =>
      //create parent folders then check their existence
      walletFile.getParentFile.mkdirs().ensuring(walletFile.getParentFile.exists())
      new MVStore.Builder().fileName(walletFile.getAbsolutePath).encryptionKey(password.toCharArray).compress().open()

    case None => new MVStore.Builder().open()
  }
```

`walletFile.getParentFile.mkdirs().ensuring(walletFile.getParentFile.exists())` throws a `java.lang.NullPointerException` if the file doesn't exists on the path

**Comment by catena2w** [comment]
In Settings.json there is a check, that wallet path is incorrect
```
 lazy val walletDirOpt = (settingsJSON \ "walletDir").asOpt[String]
    .ensuring(pathOpt => pathOpt.map(directoryEnsuring).getOrElse(true))
```
