### ISSUE TITLE
Scorex version

### ISSUE THREAD

**Issue by gagarin55** [ScorexProject/Scorex#79]
I found that Scorex doesn't have own version.
ScorexApiRoute located in Lagonaki and returns scorex version from Constants defined in Lagonaki project.

What do think about to have two verions in future - for Scorex itself and Lagonaki app ?

**Comment by catena2w** [comment]
Scorex have it's own version, you may found in https://github.com/ScorexProject/Scorex/releases or in maven (http://mvnrepository.com/artifact/org.consensusresearch/scorex-basics_2.11).

**Comment by gagarin55** [comment]
Yes, sure. But http api returns it from lagonaki.conf. Theres is no http api in Scorex

**Comment by catena2w** [comment]
You may use a lot of different libraries, the should not provide http method, that return their version. Moreover, scorex is modular framework, you may use scorex-basics-1.2.4, scorex-transaction-1.1.0 and scorex-consensus-1.2.3  in your project, there is no single Scorex version.
If you want to have API method providing version of scorex (and other libraries) - you may write your own.
