### ISSUE TITLE
Swagger UI doesn't work correctly after upgrade to akka-http

### ISSUE THREAD

**Issue by gagarin55** [ScorexProject/Scorex#81]
I've found that after upgrade to akka-http (Scorex v.1.2.5) Swagger UI started use 0.0.0.0 as host in all http request. For instance,  http://0.0.0.0:9085/addresses and so on.
Is there a solution to config swagger ui for correct host? Each node has it's own public IP address.

**Comment by catena2w** [comment]
Swagger uses "bindAddress" from your settings.json, just replace "0.0.0.0" there to correct address

**Comment by gagarin55** [comment]
But bindAddress used in NetworkController as localAddress to bind listener. It doesn't work in case when we use Elastic IP from AWS EC2 :(
