### ISSUE TITLE
Different Tx type representation as bytes array

### ISSUE THREAD

**Issue by gagarin55** [ScorexProject/Scorex#86]
I've found that when we need represent **PaymentTransaction ** as bytes array we use tx type as 1-byte array [proof](https://github.com/ScorexProject/Scorex/blob/devel/scorex-transaction/src/main/scala/scorex/transaction/PaymentTransaction.scala#L35)

```
override lazy val bytes: Array[Byte] = {
    val typeBytes = Array(TypeId.toByte)
......
```

But when we calculate singnature data we represent Tx type as 4-byte array [proof](https://github.com/ScorexProject/Scorex/blob/devel/scorex-transaction/src/main/scala/scorex/transaction/PaymentTransaction.scala#L135):

```
  private def signatureData(sender: PublicKeyAccount, recipient: Account,
                            amount: Long, fee: Long, timestamp: Long): Array[Byte] = {
    val typeBytes = Ints.toByteArray(TransactionType.PaymentTransaction.id)
......
```

Shall we use similar solution in both cases ?

**Comment by catena2w** [comment]
Not a bug actually
